WITH cte1 AS (
    SELECT 
        c.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        c.REGION,
        s.ORDER_ID,
        s.ORDER_AMOUNT,
        s.ORDER_DATE
    FROM SALES_DB.RAW.CUSTOMERS c
    LEFT JOIN SALES_DB.RAW.SALES s
        ON c.CUSTOMER_ID = s.CUSTOMER_ID
),

cte2 AS (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        REGION,
        ORDER_ID,
        ORDER_AMOUNT,
        ORDER_DATE,
        YEAR(ORDER_DATE) AS ORDER_YEAR,
        MONTH(ORDER_DATE) AS ORDER_MONTH
    FROM cte1
),

cte3 AS (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        REGION,
        ORDER_YEAR,
        ORDER_MONTH,
        SUM(ORDER_AMOUNT) AS TOTAL_SALES,
        COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
    FROM cte2
    GROUP BY 
        CUSTOMER_ID, CUSTOMER_NAME, REGION, ORDER_YEAR, ORDER_MONTH
)

SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    REGION,
    ORDER_YEAR,
    ORDER_MONTH,
    TOTAL_SALES,
    TOTAL_ORDERS
FROM cte3
ORDER BY CUSTOMER_ID, ORDER_YEAR, ORDER_MONTH;
